spring:
  cloud:
    nacos:
      server-addr: 192.168.142.128:8848     #nacos地址
    gateway:
      routes:
        - id: user-Service    #路由标示，必须唯一
          uri: lb://userservice     #路由的目标地址
          predicates:    #路由断言，判断请求是否符合规则,这个必须写
            - Path=/user/**   #判断路径是否以/user开头，如果是，则符合规则
#          filters:                            #局部过滤器
#            - AddRequestHeader=Name,zbb       #添加请求头信息
        - id: order-Service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
            - Before=2031-04-13T15:14:47.433+08:00[Asia/Shanghai]
#      default-filters:                         #全局过滤器
#        - AddRequestHeader=Name,zoubobo        #添加请求头信息
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway
server:
  port: 10086

