server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.142.128:8848   #nacos服务地址
        enabled: true
#        cluster-name: Shanghai   #集群名称，负载均衡的相关
#        namespace: 189a9cb5-d2d4-4cff-9478-8f170e56fe67       #默认是public,内容是命名空间的ID
#        ephemeral: false  #是否是临时实例,默认是true,就是临时实例，如果是false则不是临时实例,临时实例在服务出故障后会被清除，非临时实例则会一直存在
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:1314/eureka
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule   # 负载均衡规则   # 负载均衡规则,随机负载均衡
ribbon:
  eager-load:         #饥饿加载，在服务启动之后就会自动加载对应的服务，太高了响应速度（默认的是当第一次调用这个服务的时候加载（可能会影响用户体验））
    enabled: true
    clients:
      - orderservice
      - userservice
#feign的日志配置
#feign:
#  client:
#    config:
#      default:      #如果是default则是全局配置，否则则写服务名称，对应某个服务的局部配置
#        LoggerLevel: BASIC    #日志水平NONE，BASIC,HEADER,FULL
feign:
  httpclient:       #默认的是URLConnection,不支持线程池，换成apache httpclient则支持线程池
    max-connections: 200
    max-connections-per-route: 50
    enabled: true
    connection-timeout: 5000
